### ISSUE TITLE
Promise polyfill should be included as a submodule

### ISSUE THREAD

**Issue by usmonster** [niklasvh/html2canvas#494]
According to the conversation on 2afdcaf:

- [ ] Include [es6-promise](/jakearchibald/es6-promise) as a submodule dependency; depends on one or more of:
  - [x] jakearchibald/es6-promise#59
  - [x] jakearchibald/es6-promise#65
  - [x] jakearchibald/es6-promise#67
  - [x] tildeio/rsvp.js#342
- [ ] Add grunt task to optionally build h2c without Promise polyfill
- [ ] *Add tests for unpolyfilled version on browsers that natively support Promises* (maybe not?)

The [current version](/niklasvh/html2canvas/blob/2afdcaf/src/promise.js) included is just a copy-pasted old version that is no longer compliant with the official Promise spec, and which ALWAYS overwrites the native implementation due to faulty/outdated feature detection.

Updating to the most recent polyfill implementation may result in performance improvements and might also fix and/or possibly expose some subtle bugs in h2c..

**Comment by niklasvh** [comment]
This won't be necessary with #502

**Comment by usmonster** [comment]
That will be great, I'll hold off on this for now, then.

**Comment by niklasvh** [comment]
#502 is done, so closing this.

**Comment by usmonster** [comment]
Excellent!
